### PR TITLE
Add more type definitions

### PR DESCRIPTION
**Pull request by oHunewald**

### CODE REVIEW

**Review by laurentheirendt — CHANGES_REQUESTED** [review]
Looks good! May you update all the documentation headers? 👍

**Comment by oHunewald** [comment]
sure ;-)

**Comment by laurentheirendt** [comment]
Why are there all the zip and xlsx files?

**Comment by oHunewald** [comment]
Don’t know. That’s the merge from lcsb/develop


Laurent Heirendt <notifications@github.com> schrieb am Di. 25. Juni 2019 um
15:13:

**Comment by laurentheirendt** [comment]
May you rebase? Something's wrong ...

**Comment by oHunewald** [comment]
re-base? where? This was the latest dev version. should I close this PR?

**Comment by laurentheirendt** [comment]
Ok, that's how these files came in: https://github.com/LCSB-BioCore/GigaSOM.jl/pull/32/commits/ce9bd981e75b4f20c38cded9e2db4cbb7fa6241d. May you `rebase -i`?

**Pull request closed without merging**
