### PR TITLE
check length of FCS keyword names before trying to interpret them

### PR DESCRIPTION
**Pull request by exaexa**
PS. I set this to merge to `master` b/c `develop` seems like 24 commits behind, can we push it a bit?

### CODE REVIEW

**Comment by laurentheirendt** [comment]
You branched off from `master`. 24 commits are behind as they are merge commits.

**Comment by laurentheirendt** [comment]
Can you rebase this against `develop` to only get 1 commit?

**Comment by exaexa** [comment]
Rebased.

**Comment by laurentheirendt** [comment]
Nice! 👍

**Pull request merged**
