### PR TITLE
use distributed processing from DiDa

### PR DESCRIPTION
**Pull request by exaexa**
After the performance fixes in DistributedData (https://github.com/JuliaLang/julia/pull/44671#issuecomment-1072985570, https://github.com/LCSB-BioCore/DistributedData.jl/pull/40 ) it no longer seems vital to maintain a custom clone of the functionality in GigaSOM. This switches to all functions from DistributedData.

In the process of cleaning I also axed `visualizations/` as they were not even included in the code (:rofl: ) and bumped to 0.7 so that people may start depending on this.

There might be various leftovers from original gigasom-internal DiDa, esp in docs. I checked a lot with `sed` but still kinda betting on quality reviews. :D

### CODE REVIEW

**Review by laurentheirendt — APPROVED** [review]
Difficult to check every line of it, but looks good as far as I can judge

**Comment by laurentheirendt** [comment]
Why is CodeCov not responding? Would be interesting to check the testing coverage in this case

**Comment by exaexa** [comment]
I want Oliver to actually check this in his settings, let's merge after he acks that it works for him.

> Why is CodeCov not responding? Would be interesting to check the testing coverage in this case

good question, I've got no idea why it works as it works tbh. Maybe it doesn't care about merging to develop?

..............let's make our own with Julia'n'stuff? :D

**Comment by laurentheirendt** [comment]
Great - thx for fixing Codecov!

**Comment by exaexa** [comment]
So this actually seems to work just right on ULHPC so I'm going to fastforward a bit :D @oHunewald lmk in case you hit any issues.

**Pull request merged**
